In [1]:
from pop2vec.llm.src.tasks.mlm import MLM
import pandas as pd
import numpy as np
from typing import Tuple

In [2]:
from pop2vec.llm.src.new_code.custom_vocab import CustomVocabulary

/home/flavio/repositories/projects/odissei-life2vec/life-sequencing-dutch/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
data = [
    {
        "person_id": 1, 
        "segment": [2, 4, 6, 7, 8],
        "age": [18, 24, 29, 33, 56],
        "abspos": [200, 404, 500, 600, 805],
        "background": {"birth_year": "year_99.0", "birth_month": "month_12.0", "gender": "gender_2", "origin": "municipality_54.0"},
        "sentence": [ 
            ["educSim_2.0"], 
            ["_4_D"], 
            ["contractType2_1.0", "sicknessInsurance2_1.0", "wage_50.0"],
            ["contractType4_1.0", "sicknessInsurance3_1.0", "wage_10.0"],
            ["contractType1_1.0", "sicknessInsurance1_1.0", "wage_20.0"],
        ]
    },
    {
        "person_id": 2, 
        "segment": [6, 3, 10, 10, 10],
        "age": [19, 22, 40, 42, 55],
        "abspos": [99, 103, 501, 708, 890],
        "background": {"birth_year": "year_95.0", "birth_month": "month_5.0", "gender": "gender_1", "origin": "municipality_15.0"},
        "sentence": [
            ["educSim_1.0"], 
            ["contractType2_1.0", "_4_D"],
            ["contractType2_1.0", "wage_50.0", "sicknessInsurance2_2.0"] ,
            ["contractType2_1.0", "sicknessInsurance1_1.0", "wage_50.0"],
            ["contractType4_1.0", "sicknessInsurance2_0.0", "wage_10.0"],
        ]
    }
]

person_df = pd.DataFrame(data)

In [4]:
def get_vocab(person_list):
    sentence_tokens = set()
    for person in person_list:
        tokens = [token for event in person["sentence"] for token in event]
        sentence_tokens |= set(tokens) 

    background = [person["background"] for person in person_list]
    background_tokens = pd.DataFrame(background)

    general_tokens = ["[PAD]", "[CLS]", "[SEP]", "[MASK]", "[UNK]"]
    vocab = []
    
    for token in general_tokens:
        item = {"TOKEN": token, "CATEGORY": "GENERAL"}
        vocab.append(item)
    
    
    for token in sentence_tokens:
        item = {"TOKEN": token, "CATEGORY": "income_file"}
        vocab.append(item)
    
    for col in background_tokens.columns:
        for x in background_tokens[col].unique():
            item = {"TOKEN": x, "CATEGORY": "background"}
            vocab.append(item)
    
    vocab_df = pd.DataFrame(vocab)
    vocab_df["ID"] = vocab_df.index
    return vocab_df

In [5]:
vocab_df = get_vocab(data)
myvocab = CustomVocabulary(name="test", data_files=["a.csv", "b.csv"])
myvocab.vocab_df = vocab_df
myvocab.general_tokens

['[PAD]', '[CLS]', '[SEP]', '[MASK]', '[UNK]']

In [6]:
vocab_df.head(10) # masked tokens have value 3

                    TOKEN     CATEGORY  ID
0                   [PAD]      GENERAL   0
1                   [CLS]      GENERAL   1
2                   [SEP]      GENERAL   2
3                  [MASK]      GENERAL   3
4                   [UNK]      GENERAL   4
5       contractType2_1.0  income_file   5
6  sicknessInsurance2_2.0  income_file   6
7             educSim_2.0  income_file   7
8               wage_50.0  income_file   8
9             educSim_1.0  income_file   9

In [7]:
from pop2vec.llm.src.data_new.types import PersonDocument, Background

In [8]:
person_df

,person_id,segment,age,abspos,background,sentence
0,1,"[2, 4, 6, 7, 8]","[18, 24, 29, 33, 56]","[200, 404, 500, 600, 805]","{'birth_year': 'year_99.0', 'birth_month': 'mo...","[[educSim_2.0], [_4_D], [contractType2_1.0, si..."
1,2,"[6, 3, 10, 10, 10]","[19, 22, 40, 42, 55]","[99, 103, 501, 708, 890]","{'birth_year': 'year_95.0', 'birth_month': 'mo...","[[educSim_1.0], [contractType2_1.0, _4_D], [co..."

In [9]:
row = list(person_df.itertuples())[0]
person_id = getattr(row, "person_id")
sentences = row.sentence
person_document = PersonDocument(
    person_id=person_id,
    sentences=[x for x in sentences], # note: diff to original code
    abspos=[int(float(x)) for x in row.abspos],
    age=[int(float(x)) for x in row.age],
    segment=[int(x) for x in row.segment],
    background=Background(**row.background),
)

In [10]:
len(sentences)

5

In [11]:
mlm = MLM("mytest", max_length = 16, event_masking=True)
mlm.set_vocabulary(myvocab)

In [12]:
mlm

MLM(name='mytest', max_length=16, no_sep=False, p_sequence_timecut=0.0, p_sequence_resample=0.0, p_sequence_abspos_noise=0.0, p_sequence_hide_background=0.0, p_sentence_drop_tokens=0.0, shuffle_within_sentences=True, mask_ratio=0.3, smart_masking=False, event_masking=True)

In [13]:
output = mlm.encode_document(person_document, do_mlm=True)
# There is a bug -- sometimes sentences to mask returns an empty list
# this might be when the first token takes more than the limit? -> what to do about it? mask at least one token?
# what's done in the old implementation?

starting encode_document
reached reverse lengths
defined unk_id
reached do_mlm checked. do_mlm is True
calling self.mlm_mask
reached event_masking
sentence_start_pos is [ 0  5  9 13]
sentences to mask are [0]
masked_sentences are: [ 1  3  3  3  3  2 17 13 18  2 14 12 16  2]
masked tokens are: [25 23 21 19]
masked indx is: [1 2 3 4]

In [14]:
mlm

MLM(name='mytest', max_length=16, no_sep=False, p_sequence_timecut=0.0, p_sequence_resample=0.0, p_sequence_abspos_noise=0.0, p_sequence_hide_background=0.0, p_sentence_drop_tokens=0.0, shuffle_within_sentences=True, mask_ratio=0.3, smart_masking=False, event_masking=True)

In [15]:
output is None

False

In [16]:
print(len(output.input_ids))
output.input_ids[0][:40] # what are these input ids? -> they are the model predictors
output.input_ids.shape

4

(4, 16)

For each sample, `input_ids` is an array of `[4, sequence_length]`
- first row are the tokens - the masked or non-masked sequence
- the second row is the absolute position (calender time?)
- the third row is the age
- the fourth row is the segment

In [14]:
output.original_sequence[10]
# the difference between the original sequence and the input_ids is that 
# the input_ids has the target tokens removed

18

In [15]:
output.target_pos # this is the index in the sequence that is masked

array([2, 1, 3, 6])

In [16]:
output.target_pos.min()

1

In [17]:
output.target_tokens # this is the value of the masked tokens to be predicted

array([23., 25., 21.,  9.])

In [18]:
def print_target_position(idx, encoded_document):
    print(f"position {idx} in the original sequence with value {encoded_document.original_sequence[idx]} is a target token")

In [19]:
print_target_position(1, output)
print_target_position(4, output)

position 1 in the original sequence with value 25 is a target token
position 4 in the original sequence with value 19 is a target token

In [20]:
output.input_ids[0, 1]
output.input_ids[1,1] # this is the absolute position of the masked token 
output.input_ids[2,1] # this is the age of the masked token
output.input_ids[3,1] # this is the segment of the masked token
# but something is still not right? why is the age 0
# output.original_sequence[1]

0.0

Checking a single token
- background tokens have 0s for age, abspos etc - makes sense

In [21]:
first_token = output.input_ids[:, 10]

In [22]:
first_token

array([ 18., 600.,  33.,   7.])

In [23]:
output.padding_mask[4] # True indicates NOT padding token

True

In [24]:
vocab_df # want tokens between 5 and 18

                     TOKEN     CATEGORY  ID
0                    [PAD]      GENERAL   0
1                    [CLS]      GENERAL   1
2                    [SEP]      GENERAL   2
3                   [MASK]      GENERAL   3
4                    [UNK]      GENERAL   4
5                wage_20.0  income_file   5
6        contractType1_1.0  income_file   6
7   sicknessInsurance2_2.0  income_file   7
8   sicknessInsurance2_1.0  income_file   8
9        contractType2_1.0  income_file   9
10             educSim_2.0  income_file  10
11               wage_50.0  income_file  11
12  sicknessInsurance2_0.0  income_file  12
13       contractType4_1.0  income_file  13
14               wage_10.0  income_file  14
15  sicknessInsurance1_1.0  income_file  15
16             educSim_1.0  income_file  16
17  sicknessInsurance3_1.0  income_file  17
18                    _4_D  income_file  18
19               year_99.0   background  19
20               year_95.0   background  20
21              month_12.0   background  21
22               month_5.0   background  22
23                gender_2   background  23
24                gender_1   background  24
25       municipality_54.0   background  25
26       municipality_15.0   background  26

### Understand the masking

calling the `MLM.mlm_mask`
- passes in token_ids, which can be extracted from the original_sequence for those tokens that are not
    - originally, the token ids come from mapping the string tokens to token IDs
- we will need to take care of the background tokens as well as of the "event" tokens - do we want event-mask all of them? (how many tokens does a background event have? -> I guess it makes sense to mask the entire background, so that the model learns to predict the entire background from the entire life sequence?

### Implement event-level (whole-sentence) masking

First, we recover the token ids from the original sequence

In [25]:
token_ids = output.original_sequence[output.padding_mask]

In [26]:
token_ids

array([ 1, 25, 23, 21, 19,  2, 17,  6, 13,  2,  8,  7,  5,  2])

Instead of indexes to mask, we need a list of events, and their lengths. then we sample a fraction of events to mask, apply the mask identifier to all of the tokens in the respective events, and add them to the target tokens.
- 2 indicates a separator

In [27]:
def find_sentences_to_mask(
        token_sequence: np.ndarray,
        sep_token: int,
        mask_frac: float,
        ignore_tokens: np.ndarray = np.asarray([0,1,2,3,4]) # these should be the GENERAL tokens
        # they are used to determine the start of the first sentence that could be potentially masked
    ) -> Tuple[np.ndarray, np.ndarray]:
    """Determine random set of sentences to be masked.

    Args:
        token_sequence (np.ndarray): the sequence of tokens to mask.
        sep_token (int): the identifier of the SEP token.
        mask_frac (float): the fraction of tokens to be masked. Must be between 0 and 1.
        ignore_tokens (np.ndarray): tokens to be ignored at the jjkstart of the sequence. 
            Concerns the CLS token at the start of the sequence, and possibly others.

    Returns:
        A tuple of numpy arrays. 
        - The first entry are the start/end positions of sentence: The position of the `sep_tokens` and the 
            last `ignore_token` before the first sentence starts.
        - The second are the sentences selected for masking.
    """
    n_tokens = len(token_sequence)
    idx_sentence_sep = np.nonzero(token_sequence == sep_token)[0]
    sentence_lengths = np.hstack((idx_sentence_sep[0], np.diff(idx_sentence_sep)))
    
    sentence_ids = np.arange(len(idx_sentence_sep) - 1) # the last SEP token is the end of the sequence
    np.random.shuffle(sentence_ids)

    lengths_shuffled = sentence_lengths[sentence_ids]
    lengths_cumsum = np.cumsum(lengths_shuffled)
    sentences_to_mask = lengths_cumsum / n_tokens <= mask_frac

    pos_first_relevant_token = np.min(np.nonzero(~np.isin(token_sequence, ignore_tokens))) - 1 # we'll ignore the sep tokens for masking (?)
    sentence_starts_and_ends = np.hstack((pos_first_relevant_token, idx_sentence_sep))
    return sentence_starts_and_ends, np.sort(sentence_ids[sentences_to_mask])

    
def sentence_masking(
         token_sequence: np.ndarray,
         sentence_starts_and_ends: np.ndarray, 
         sentences_to_mask: np.ndarray,
         mask_id: int
    ) -> Tuple[np.ndarray, np.ndarray]:
    """Mask all tokens belonging to the same sentences.

    Args:
        token_sequence (np.ndarray): sequence of tokens to be masked.
        sentence_starts_and_ends (np.ndarray): the indices of non-sentence tokens surrounding sentences. 
            These are SEP tokens, and any general token before the first sentence. Masking a whole 
            sentence will mask all tokens *between* two surrounding, non-sentence tokens.
        sentences_to_mask (np.ndarray): indices of sentences, among all sentences, to be masked.
        mask_id (int): the token ID for the mask.

    Returns: A tuple of np.ndarrays:
    - The first entry is the masked sequence
    - The second entry are the indices of the masked tokens
    - The third entry are the true values of the masked tokens    
    """
    masking_idx_start = sentence_starts_and_ends[sentences_to_mask]
    print(masking_idx_start)
    masking_idx_stop = sentence_starts_and_ends[sentences_to_mask + 1]
    print(masking_idx_stop)
    token_indices = np.arange(len(token_sequence))

    mask = (token_indices[:, None] > masking_idx_start) & (token_indices[:, None] < masking_idx_stop)
    mask = mask.any(axis=1)

    masked_sequence = token_sequence.copy()
    masked_sequence[mask] = mask_id
    target_tokens = token_sequence[mask]
    target_idx = np.nonzero(mask)[0]

    return masked_sequence, target_idx, target_tokens

In [28]:
sentence_start_pos, sentences_to_mask = find_sentences_to_mask(token_ids, 2, 0.5)
sentence_start_pos

array([ 0,  5,  9, 13])

In [29]:
sentences_to_mask # these are also the starting indexes for masking

array([1])

In [30]:
sentence_start_pos

array([ 0,  5,  9, 13])

In [31]:
sentence_masking(token_ids, sentence_start_pos, sentences_to_mask, 3)

[5]
[9]

(array([ 1, 25, 23, 21, 19,  2,  3,  3,  3,  2,  8,  7,  5,  2]),
 array([6, 7, 8]),
 array([17,  6, 13]))

In [32]:
token_ids

array([ 1, 25, 23, 21, 19,  2, 17,  6, 13,  2,  8,  7,  5,  2])

In [17]:
ignore_tokens = myvocab.general_tokens
ignore_tokens
token2index = myvocab.token2index
token2index

{'[PAD]': 0,
 '[CLS]': 1,
 '[SEP]': 2,
 '[MASK]': 3,
 '[UNK]': 4,
 'sicknessInsurance3_1.0': 5,
 'sicknessInsurance1_1.0': 6,
 'educSim_1.0': 7,
 'sicknessInsurance2_1.0': 8,
 'sicknessInsurance2_0.0': 9,
 '_4_D': 10,
 'wage_50.0': 11,
 'wage_20.0': 12,
 'wage_10.0': 13,
 'contractType2_1.0': 14,
 'educSim_2.0': 15,
 'sicknessInsurance2_2.0': 16,
 'contractType4_1.0': 17,
 'contractType1_1.0': 18,
 'year_99.0': 19,
 'year_95.0': 20,
 'month_12.0': 21,
 'month_5.0': 22,
 'gender_2': 23,
 'gender_1': 24,
 'municipality_54.0': 25,
 'municipality_15.0': 26}

In [18]:
[token2index[x] for x in ignore_tokens]

[0, 1, 2, 3, 4]

In [16]:
np.any([False, False, False])

False

---------------

In [46]:
idx_sep = np.nonzero(token_ids == 2)[0]
total_length = len(token_ids)
mask_frac = 0.5
idx_sep
n_sentences = len(idx_sep)
n_sentences
print(idx_sep)
sentence_lengths = np.hstack((idx_sep[0], np.diff(idx_sep)))
sentence_lengths
sentence_idx = np.arange(len(idx_sep))
np.random.shuffle(sentence_idx)
print(sentence_idx)
lengths_shuffled = sentence_lengths[sentence_idx]
lengths_cumsum = np.cumsum(lengths_shuffled)
sentences_to_mask = lengths_cumsum / total_length <= mask_frac
sentences_to_mask

[ 5  9 13]
[2 1 0]

array([ True, False, False])

In [47]:
sentence_idx[sentences_to_mask]

array([2])

In [48]:
np.random.shuffle(idx_sep)
idx_sep

array([ 9, 13,  5])

In [49]:
n_sent_to_mask = 2 # perhaps better define a fraction? also, we don't want so sample the stop word
# because it's not followed by anything?
start_idx_sent_mask = np.sort(np.random.choice(idx_sep[:-1], n_sent_to_mask, replace=False))
# now we need the positions of all masked tokens
start_idx_sent_mask
masked = np.zeros_like(token_ids)
masked

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
print(f"start indices of sentence mask: {start_idx_sent_mask}")
print(f"all sentences starting indices: {idx_sep}")

start indices of sentence mask: [ 9 13]
all sentences starting indices: [ 9 13  5]

In [51]:
start_indices = np.where(np.isin(idx_sep, start_idx_sent_mask))[0]
end_indices = start_indices + 1
start_indices
# end_indices

array([0, 1])

In [52]:
idx_sep[start_indices]
idx_sep[end_indices]

array([13,  5])

In [53]:
idx_sep

array([ 9, 13,  5])

In [54]:
all_indices = np.arange(token_ids.shape[0])
all_indices

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [56]:
mask = (all_indices[:, None] > idx_sep[start_indices]) & (all_indices[:, None] < idx_sep[end_indices])
mask = mask.any(axis=1)
mask_id = 3 # TODO -- do not hand code
input_tokens = token_ids.copy()
input_tokens[mask] = mask_id
input_tokens
target_tokens = token_ids[mask]
target_tokens
y_indx = np.nonzero(mask)[0]

### we need token_ids, y_indx, y_token. in the code above, 
- y_token are the target_tokens I think
- token_ids are the input_tokens
- y_indx is the mask I think?

#### What else to consider
- mix masking: single token vs whole event?
- map to "fraction" masked -> just take the cumulative length of the sampled events until it reaches the specified fraction

In [69]:
all_indices.shape

(14,)

In [68]:
(all_indices[:, None] > np.asarray([9,13]))

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [60]:
idx_sep[start_indices].shape

(2,)

In [62]:
np.asarray([9,13]).shape

(2,)

In [60]:
import torch
import numpy as np

In [66]:
y = np.array([3,4,5])
print(torch.from_numpy(y).long().dtype)
print(torch.from_numpy(y).dtype)
print(torch.from_numpy(y).float().dtype)

torch.int64
torch.int64
torch.float32

- sentence
	- array of arrays. each array is an event. each event has string tokens such as `['INPAINV3400P_93', 'INPEMEZ_Others', 'INPKKGEM_Others', 'INPPH770UP_93']`
- abspos
	- `[2864, 6289, ]` -> increasing set of integers
	- one integer for each event
- age
	- `[32, 49, ...]` -> one age for each event
- segment
	- array of `2` for each event - unclear what it is
- background
	- `{"birth_month": "month_4", "birth_year": "year_1989", "gender": "gender_male"}`


```txt
TOKEN,CATEGORY,ID
[PAD],GENERAL,0
[CLS],GENERAL,1
[SEP],GENERAL,2
[MASK],GENERAL,3
[UNK],GENERAL,4
gender_1,BACKGROUND,5
gender_2,BACKGROUND,6
gender_MISSING,BACKGROUND,7
year_1958,background_shuffled_year,8
year_1962,background_shuffled_year,9
year_2003,background_shuffled_year,10
year_1961,background_shuffled_year,11
year_1952,background_shuffled_year,12
year_1971,background_shuffled_year,13
year_1991,background_shuffled_year,14
year_2016,background_shuffled_year,15
year_1965,background_shuffled_year,16
year_2008,background_shuffled_year,17
year_1963,background_shuffled_year,18
```

category refers to `filename_colname`; token consists of `colname_content`